name: Build and Create Installer

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  INSTALLER_NAME: btmnr

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Install NSIS
      run: |
        choco install nsis -y
        
    - name: Build Release
      run: cargo build --release
      
    - name: Prepare Install Files
      run: |
        mkdir installer
        copy target\release\btmnr.exe installer\
        copy config.json installer\
        copy README.md installer\
        
    - name: Create Installer
      run: |
        dir
        makensis /DPRODUCT_VERSION="${{ github.ref_name }}" installer.nsi
        dir

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.INSTALLER_NAME }}-installer
        path: ${{ env.INSTALLER_NAME }}-setup.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.INSTALLER_NAME }}-setup.exe
