name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Rust versions
      id: rust-version
      run: |
        echo "rustc=$(rustc -V)" >> $GITHUB_OUTPUT
        echo "cargo=$(cargo -V)" >> $GITHUB_OUTPUT
        echo "rustup=$(rustup -V)" >> $GITHUB_OUTPUT
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --release
      
    - name: Run tests
      run: cargo test --all
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: btmnr
        path: |
          target/release/btmnr.exe
          config.json
