name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: |
        cargo build --release
        echo "build_status=success" >> $GITHUB_ENV
      
    - name: Run tests
      if: env.build_status == 'success'
      run: |
        cargo test --all
        echo "test_status=success" >> $GITHUB_ENV
      
    - name: Upload artifacts
      if: env.test_status == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: bluetooth-manager-windows
        path: |
          target/release/btmnr.exe
          config.json
